groups:
  - name: kong_gateway
    rules:
      - alert: KongGatewayDown
        expr: up{job="kong"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Kong Gateway is down"
          description: "Kong Gateway has been down for more than 1 minute."

      - alert: KongHighRequestRate
        expr: rate(kong_http_requests_total[5m]) > 1000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High request rate to Kong Gateway"
          description: "Kong Gateway is receiving {{ $value }} requests per second."

      - alert: KongHighErrorRate
        expr: rate(kong_http_requests_total{code=~"5.."}[5m]) > 10
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate in Kong Gateway"
          description: "Kong Gateway error rate is {{ $value }} errors per second."

      - alert: KongHighLatency
        expr: histogram_quantile(0.95, rate(kong_request_latency_ms_bucket[5m])) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency in Kong Gateway"
          description: "Kong Gateway 95th percentile latency is {{ $value }}ms."

      - alert: KongDatabaseConnectionError
        expr: kong_database_reachable == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Kong database connection error"
          description: "Kong Gateway cannot connect to the database."

      - alert: KongUpstreamUnhealthy
        expr: kong_upstream_target_health == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Kong upstream target unhealthy"
          description: "Upstream target {{ $labels.upstream }} is unhealthy."

  - name: kong_performance
    rules:
      - record: kong:request_rate_5m
        expr: rate(kong_http_requests_total[5m])

      - record: kong:error_rate_5m
        expr: rate(kong_http_requests_total{code=~"5.."}[5m])

      - record: kong:latency_95th_5m
        expr: histogram_quantile(0.95, rate(kong_request_latency_ms_bucket[5m]))

      - record: kong:latency_99th_5m
        expr: histogram_quantile(0.99, rate(kong_request_latency_ms_bucket[5m]))

  - name: kong_security
    rules:
      - alert: KongUnauthorizedRequests
        expr: rate(kong_http_requests_total{code="401"}[5m]) > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High number of unauthorized requests"
          description: "{{ $value }} unauthorized requests per second to Kong Gateway."

      - alert: KongRateLimitExceeded
        expr: rate(kong_http_requests_total{code="429"}[5m]) > 10
        for: 1m
        labels:
          severity: info
        annotations:
          summary: "Rate limit exceeded"
          description: "{{ $value }} requests per second are being rate limited."

      - alert: KongSuspiciousTraffic
        expr: rate(kong_http_requests_total{code=~"4.."}[5m]) > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of client errors"
          description: "{{ $value }} client errors per second, possible attack or misconfiguration."