apiVersion: v2
name: plugin-orchestrator
description: A Helm chart for Plugin Pipeline Orchestrator - Enterprise-grade plugin deployment and management system
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/your-org/saas-idp
sources:
  - https://github.com/your-org/saas-idp/tree/main/infrastructure/plugin-pipeline
keywords:
  - plugin
  - orchestrator
  - deployment
  - kubernetes
  - backstage
  - platform-engineering
maintainers:
  - name: Platform Engineering Team
    email: platform-engineering@example.com
  - name: SRE Team
    email: sre@example.com
icon: https://example.com/icons/plugin-orchestrator.png
annotations:
  category: Platform Engineering
  licenses: Apache-2.0
dependencies:
  - name: postgresql
    version: "12.1.9"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.3.7"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: prometheus
    version: "15.18.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    alias: kube-prometheus-stack
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.50.7"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled
  - name: jaeger
    version: "0.71.2"
    repository: "https://jaegertracing.github.io/helm-charts"
    condition: tracing.jaeger.enabled