
# Production overrides for plugin-orchestrator

global:
  imageRegistry: "your-docker-registry"

pluginOrchestrator:
  replicaCount: 3
  image:
    repository: "your-docker-registry/plugin-orchestrator"
    tag: "1.0.0"
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi

postgresql:
  enabled: false

redis:
  enabled: false

monitoring:
  enabled: true
