apiVersion: v2
name: portal
description: Enhanced Plugin Management System for Internal Developer Portal
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://portal.company.com
sources:
  - https://github.com/company/portal-infrastructure
maintainers:
  - name: Platform Team
    email: platform-team@company.com
    url: https://docs.portal.company.com
keywords:
  - developer-portal
  - backstage
  - plugin-management
  - platform-engineering
annotations:
  category: Application
  licenses: Apache-2.0
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "18.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: "25.x.x"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "7.x.x"
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled